# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime

from pydantic import Field as FieldInfo

from ..._models import BaseModel
from .gateway_status import GatewayStatus
from .gateway_router_state import GatewayRouterState

__all__ = ["GatewayRouter"]


class GatewayRouter(BaseModel):
    aliases: Optional[List[str]] = None

    auto_generated: Optional[bool] = FieldInfo(alias="autoGenerated", default=None)
    """
    auto_generated indicates this router was generated by the system for a
    deployment. Auto-generated routers cannot be updated or deleted by the user.
    """

    created_by: Optional[str] = FieldInfo(alias="createdBy", default=None)

    create_time: Optional[datetime] = FieldInfo(alias="createTime", default=None)

    deployments: Optional[List[str]] = None
    """The deployment names to be covered by the router."""

    display_name: Optional[str] = FieldInfo(alias="displayName", default=None)

    even_load: Optional[object] = FieldInfo(alias="evenLoad", default=None)
    """
    Dynamically adjust traffic allocation to balance the load per replica across the
    deployments as much as possible.
    """

    model: Optional[str] = None
    """
    The model name to route requests to. model is only applicable to single-region
    deployments. For multi-region deployments, model must be empty.
    """

    name: Optional[str] = None

    state: Optional[GatewayRouterState] = None
    """The state of the router."""

    status: Optional[GatewayStatus] = None

    weighted_random: Optional[object] = FieldInfo(alias="weightedRandom", default=None)
    """Use replica count as weight."""
