# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional

from ..._models import BaseModel
from .chat_completion_message_tool_call import ChatCompletionMessageToolCall

__all__ = ["ChatMessage", "ContentUnionMember1", "ContentUnionMember1ImageURL", "ContentUnionMember1VideoURL"]


class ContentUnionMember1ImageURL(BaseModel):
    url: str
    """Image link or base64 data URI.

    `mm_file://{file_id}` is also accepted for assets uploaded via the Files API.
    """

    detail: Optional[str] = None
    """Detail level for image understanding.

    One of `low` / `default` / `high` (model-specific defaults table). Used to pick
    a default `max_long_side_pixel` when that field is absent.
    """

    max_long_side_pixel: Optional[int] = None
    """Per-image cap on the long side after resizing.

    When omitted, the model derives a default from `detail`. Currently honored by
    MiniMax M3 VL preprocessing; other VL models ignore this field. See the M3 VL
    preprocessing spec (2026-05-29) for the full 3-step resize semantics (long-side
    cap → short-side floor at 112 px → hard total-pixel cap).
    """


class ContentUnionMember1VideoURL(BaseModel):
    url: str
    """Video link or base64 data URI.

    `mm_file://{file_id}` is accepted for assets uploaded via the Files API
    (recommended for files > 50 MB).
    """

    detail: Optional[str] = None
    """Detail level for video understanding. One of `low` / `default` / `high`."""

    fps: Optional[float] = None
    """
    Frame sampling rate, in [0.2, 5] Hz for MiniMax M3 VL (was [0.5, 2] in the
    pre-2026-05-29 spec). Higher values are more sensitive to motion at the cost of
    more tokens; lower values are cheaper but less responsive to fast scene changes.
    Equivalent to `sample_fps` on non-M3 video models.
    """

    max_frames: Optional[int] = None

    max_long_side_pixel: Optional[int] = None
    """Per-frame cap on the long side after resizing.

    When omitted, the model derives a default from `detail`. Currently honored by
    MiniMax M3 VL preprocessing; other VL models ignore this field.
    """

    sample_fps: Optional[float] = None
    """Frame sampling rate (Kimi K2.5 VL legacy name).

    For MiniMax M3 VL prefer the canonical `fps` field.
    """

    spatial_limit: Optional[int] = None


class ContentUnionMember1(BaseModel):
    type: str

    image_url: Optional[ContentUnionMember1ImageURL] = None

    text: Optional[str] = None

    video_url: Optional[ContentUnionMember1VideoURL] = None


class ChatMessage(BaseModel):
    """A chat completion message."""

    role: str
    """The role of the messages author. One of `system`, `user`, or `assistant`."""

    content: Union[str, List[ContentUnionMember1], None] = None
    """The contents of the message.

    `content` is required for all messages, and may be null for assistant messages
    with function calls.
    """

    reasoning_content: Optional[str] = None
    """The reasoning or thinking process generated by the model.

    This field is only available for certain reasoning models (GLM 4.5, GLM 4.5 Air,
    GPT OSS 120B, GPT OSS 20B) and contains the model's internal reasoning that
    would otherwise appear in `<think></think>` tags within the content field.
    """

    tool_call_id: Optional[str] = None

    tool_calls: Optional[List[ChatCompletionMessageToolCall]] = None
    """The tool calls generated by the model, such as function calls."""
