configured_endpoints: 89
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/fireworks-ai%2Ffireworks-ai-e5a236c1c496fc010c79c2d7c3ada42e0c625b8491ec6f8341f83ba78cffe9d4.yml
openapi_spec_hash: 3a7598e248b66b288f735c9e79e7fec1
config_hash: d54edfeeb84ccf2a1357eece85acaf7b
