configured_endpoints: 62
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/fireworks-ai%2Ffireworks-ai-2bf1243091ea03a54521d6fba7f8b700b38fdaf7e3b9565ad00ba38b4bacabf6.yml
openapi_spec_hash: c69f3157dfe2644a120f9db412f75009
config_hash: ee50be868a7d2c1fe0756fff5bacfb8e
