# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from ..._types import SequenceNotStr
from ..shared_params.chat_message import ChatMessage
from ..shared_params.chat_completion_tool import ChatCompletionTool

__all__ = [
    "CompletionCreateParamsBase",
    "FunctionCall",
    "FunctionCallFunctionNameSpec",
    "Function",
    "Prediction",
    "PredictionPredictedOutput",
    "PredictionPredictedOutputContentUnionMember1",
    "PredictionPredictedOutputContentUnionMember1ImageURL",
    "PredictionPredictedOutputContentUnionMember1VideoURL",
    "ResponseFormat",
    "StreamOptions",
    "Thinking",
    "ThinkingThinkingConfigEnabled",
    "ThinkingThinkingConfigDisabled",
    "ThinkingThinkingConfigAdaptive",
    "ToolChoice",
    "ToolChoiceFunctionSelection",
    "ToolChoiceFunctionSelectionFunction",
    "ToolChoiceAllowedToolsSelection",
    "ToolChoiceAllowedToolsSelectionAllowedTools",
    "CompletionCreateParamsNonStreaming",
    "CompletionCreateParamsStreaming",
]


class CompletionCreateParamsBase(TypedDict, total=False):
    model: Required[str]
    """The name of the model to use.

    Example: `"accounts/fireworks/models/kimi-k2-instruct-0905"`
    """

    context_length_exceeded_behavior: Literal["error", "truncate"]
    """
    What to do if the token count of prompt plus `max_tokens` exceeds the model's
    context window.

    Passing `truncate` limits the `max_tokens` to at most
    `context_window_length - prompt_length`. This is the default.

    Passing `error` would trigger a request error.

    The default of `'truncate'` is selected as it allows to ask for high
    `max_tokens` value while respecting the context window length without having to
    do client-side prompt tokenization.

    Note, that it differs from OpenAI's behavior that matches that of `error`.
    """

    echo: Optional[bool]
    """Echo back the prompt in addition to the completion."""

    echo_last: Optional[int]
    """Echo back the last N tokens of the prompt in addition to the completion.

    This is useful for obtaining logprobs of the prompt suffix but without
    transferring too much data. Passing `echo_last=len(prompt)` is the same as
    `echo=True`
    """

    frequency_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on their existing frequency in the
    text so far, decreasing the model's likelihood to repeat the same line verbatim.

    Reasonable value is around 0.1 to 1 if the aim is to just reduce repetitive
    samples somewhat. If the aim is to strongly suppress repetition, then one can
    increase the coefficients up to 2, but this can noticeably degrade the quality
    of samples. Negative values can be used to increase the likelihood of
    repetition.

    See also `presence_penalty` for penalizing tokens that have at least one
    appearance at a fixed rate.

    OpenAI compatible (follows OpenAI's conventions for handling token frequency and
    repetition penalties).

    Required range: `-2 <= x <= 2`
    """

    function_call: Optional[FunctionCall]
    """Deprecated in OpenAI.

    Use 'tool_choice' instead. This will be automatically transformed to
    tool_choice.
    """

    functions: Iterable[Function]
    """Deprecated in OpenAI.

    Use 'tools' instead. This will be automatically transformed to tools.
    """

    ignore_eos: bool
    """
    This setting controls whether the model should ignore the End of Sequence (EOS)
    token. When set to `True`, the model will continue generating tokens even after
    the EOS token is produced. By default, it stops when the EOS token is reached.
    """

    logit_bias: Optional[Dict[str, float]]
    """Modify the likelihood of specified tokens appearing in the completion.

    Accepts a json object that maps tokens (specified by their token ID in the
    tokenizer) to an associated bias value from -100 to 100. Mathematically, the
    bias is added to the logits generated by the model prior to sampling.
    """

    logprobs: Union[int, bool, None]
    """Include log probabilities in the response.

    This accepts either a boolean or an integer:

    If set to `true`, log probabilities are included and the number of alternatives
    can be controlled via `top_logprobs` (OpenAI-compatible behavior).

    If set to an integer N, include log probabilities for up to N most likely tokens
    per position in the legacy format. N must be between 0 and the deployment's
    `--max-logprobs` limit (5 by default).

    The API will always return the logprob of the sampled token, so there may be up
    to `logprobs+1` elements in the response when an integer is used.
    """

    max_completion_tokens: Optional[int]
    """Alias for max_tokens. Cannot be specified together with max_tokens."""

    max_tokens: Optional[int]
    """The maximum number of tokens to generate in the completion.

    If the token count of your prompt plus max_tokens exceeds the model's context
    length, the behavior depends on context_length_exceeded_behavior. By default,
    max_tokens will be lowered to fit in the context window instead of returning an
    error.
    """

    messages: Iterable[ChatMessage]
    """A list of messages comprising the conversation so far.

    When `prompt_token_ids` is supplied this field is ignored (the caller is taking
    responsibility for chat-template rendering and tokenization upstream).
    """

    metadata: Optional[Dict[str, str]]
    """Additional metadata to store with the request for tracing/distillation."""

    min_p: Optional[float]
    """Minimum probability threshold for token selection.

    Only tokens with probability >= min_p are considered for selection. This is an
    alternative to `top_p` and `top_k` sampling.

    Required range: `0 <= x <= 1`
    """

    mirostat_lr: Optional[float]
    """
    Specifies the learning rate for the Mirostat sampling algorithm, which controls
    how quickly the model adjusts its token distribution to maintain the target
    perplexity. A smaller value slows down the adjustments, leading to more stable
    but gradual shifts, while higher values speed up corrections at the cost of
    potential instability.
    """

    mirostat_target: Optional[float]
    """Defines the target perplexity for the Mirostat algorithm.

    Perplexity measures the unpredictability of the generated text, with higher
    values encouraging more diverse and creative outputs, while lower values
    prioritize predictability and coherence. The algorithm dynamically adjusts the
    token selection to maintain this target during text generation.

    If not specified, Mirostat sampling is disabled.
    """

    n: int
    """How many completions to generate for each prompt.

    **Note:** Because this parameter generates many completions, it can quickly
    consume your token quota. Use carefully and ensure that you have reasonable
    settings for `max_tokens` and `stop`.

    Required range: `1 <= x <= 128`

    Example: `1`
    """

    parallel_tool_calls: Optional[bool]
    """Enable parallel function calling."""

    perf_metrics_in_response: Optional[bool]
    """Whether to include performance metrics in the response body.

    **Non-streaming requests:** Performance metrics are always included in response
    headers (e.g., `fireworks-prompt-tokens`,
    `fireworks-server-time-to-first-token`). Setting this to `true` additionally
    includes the same metrics in the response body under the `perf_metrics` field.

    **Streaming requests:** Performance metrics are only included in the response
    body under the `perf_metrics` field in the final chunk (when `finish_reason` is
    set). This is because headers may not be accessible during streaming.

    The response body `perf_metrics` field contains the following metrics:

    **Basic Metrics (all deployments):**

    - `prompt-tokens`: Number of tokens in the prompt
    - `cached-prompt-tokens`: Number of cached prompt tokens
    - `server-time-to-first-token`: Time from request start to first token (in
      seconds)
    - `server-processing-time`: Total processing time (in seconds, only for
      completed requests)

    **Predicted Outputs Metrics:**

    - `speculation-prompt-tokens`: Number of speculative prompt tokens
    - `speculation-prompt-matched-tokens`: Number of matched speculative prompt
      tokens (for completed requests)

    **Dedicated Deployment Only Metrics:**

    - `speculation-generated-tokens`: Number of speculative generated tokens (for
      completed requests)
    - `speculation-acceptance`: Speculation acceptance rates by position
    - `backend-host`: Hostname of the backend server
    - `num-concurrent-requests`: Number of concurrent requests
    - `deployment`: Deployment name
    - `tokenizer-queue-duration`: Time spent in tokenizer queue
    - `tokenizer-duration`: Time spent in tokenizer
    - `prefill-queue-duration`: Time spent in prefill queue
    - `prefill-duration`: Time spent in prefill
    - `generation-queue-duration`: Time spent in generation queue
    - `generation-duration`: Time spent in generation
    """

    prediction: Optional[Prediction]
    """OpenAI-compatible predicted output for speculative decoding.

    Can be a PredictedOutput object or a simple string. Automatically transformed to
    speculation.
    """

    presence_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on whether they appear in the text so
    far, increasing the model's likelihood to talk about new topics.

    Reasonable value is around 0.1 to 1 if the aim is to just reduce repetitive
    samples somewhat. If the aim is to strongly suppress repetition, then one can
    increase the coefficients up to 2, but this can noticeably degrade the quality
    of samples. Negative values can be used to increase the likelihood of
    repetition.

    See also `frequency_penalty` for penalizing tokens at an increasing rate
    depending on how often they appear.

    OpenAI compatible (follows OpenAI's conventions for handling token frequency and
    repetition penalties).

    Required range: `-2 <= x <= 2`
    """

    prompt_cache_isolation_key: Optional[str]
    """Isolation key for prompt caching to separate cache entries."""

    prompt_cache_key: Optional[str]
    """A key used for prompt caching session affinity.

    Requests with the same prompt_cache_key are routed to the same backend to
    maximize KV cache hit rates. This is the preferred field for session affinity
    (takes priority over the 'user' field).
    """

    prompt_token_ids: Optional[Iterable[int]]
    """Pre-tokenized prompt.

    When set, the server skips chat-template rendering and tokenization for the
    input — the supplied token IDs are fed directly to generation. Generation, the
    response formatter (incl. `--formatter-backend vllm` parsers), and tool-call
    routing all run as usual on the model's output.

    Intended for upstream gateways (e.g. dynamo) that own the tokenizer and chat
    template, and want this server only to generate and format. Mutually exclusive
    with `messages`: passing both is a 400.
    """

    prompt_truncate_len: Optional[int]
    """The size (in tokens) to which to truncate chat prompts.

    This includes the system prompt (if any), previous user/assistant messages, and
    the current user message. Earlier user/assistant messages will be evicted first
    to fit the prompt into this length. The system prompt is preserved whenever
    possible and only truncated as a last resort.

    This should usually be set to a number much smaller << than the model's maximum
    context size, to allow enough remaining tokens for generating a response.

    If omitted, you may receive "prompt too long" errors in your responses as
    conversations grow. Note that even with this set, you may still receive "prompt
    too long" errors if individual messages (such as a very long system prompt or
    user message) exceed the model's context window on their own.
    """

    raw_output: Optional[bool]
    """Return raw output from the model."""

    reasoning_effort: Union[Literal["low", "medium", "high", "xhigh", "max", "none", "adaptive"], int, bool, None]
    """Controls reasoning behavior for supported models.

    When enabled, the model's reasoning appears in the `reasoning_content` field of
    the response, separate from the final answer in `content`.

    **Accepted values:**

    - **String** (OpenAI-compatible): `'low'`, `'medium'`, `'high'`, or `'max'` to
      enable reasoning with varying effort levels; `'none'` to disable reasoning.
    - **Boolean** (Fireworks extension): `true` to enable reasoning, `false` to
      disable it.
    - **Integer** (Fireworks extension): A positive integer to set a hard token
      limit on reasoning output. Integer values enable the model's normal
      medium-style thinking behavior and force the model to end its thinking phase
      after at most that many generated thinking tokens.

    **Important:** Boolean values are normalized internally: `true` becomes
    `'medium'`, and `false` becomes `'none'`. This normalization happens before
    model-specific validation, so if a model doesn't support `'none'`, passing
    `false` will produce an error referencing `'none'`.

    **Model-specific behavior:**

    - **Qwen3**: Grammar-based reasoning on the reasoning-enabled `qwen3`/`qwen3p5`
      conversation styles. Older chat-mode Qwen3 deployments may opt into
      `qwen3-no-thinking`, which disables reasoning support. For reasoning-enabled
      styles, use `'none'` or `false` to disable. Supports integer token limits to
      cap reasoning output. `'low'`, `'medium'`, and `'high'` keep their
      model-specific behavior and are not hard budgets.
    - **MiniMax M2**: Reasoning is required (always on). Defaults to `'medium'` when
      omitted. Accepts only string `reasoning_effort`: `'low'`, `'medium'`, or
      `'high'`. `'none'` and boolean values are rejected.
    - **DeepSeek V3.1**: Binary on/off reasoning. Default reasoning off (matches
      chat template). Use `true`, `'low'`, `'medium'`, or `'high'` to enable;
      `'none'` or `false` to disable.
    - **DeepSeek V3.2**: Binary on/off reasoning. Default reasoning on. Use `'none'`
      or `false` to disable; effort levels and integers have no additional effect.
    - **DeepSeek V4**: Accepts `'none'`, `'low'`, `'medium'`, `'high'`, `'xhigh'`,
      and `'max'`. Default reasoning on (`'high'`). `'xhigh'` is silently promoted
      to `'max'`. `'max'` prepends a thorough-reasoning preamble; `'high'` enables
      thinking. `'low'` and `'medium'` are silently promoted to `'high'`. `'none'`
      or `false` disables thinking.
    - **GLM 4.5, GLM 4.5 Air, GLM 4.6, GLM 4.7, GLM 5.1**: Binary on/off reasoning.
      Default reasoning on. Use `'none'` or `false` to disable; effort levels and
      integers have no additional effect.
    - **GLM 5.2**: Two thinking tiers, `High` and `Max` (rendered as a
      `Reasoning Effort:` system line). `'high'` selects High; `'low'` and
      `'medium'` are collapsed to `'high'`; `'max'` and `'xhigh'` select Max; when
      omitted, the model default (`Max`) applies. `'none'` or `false` disables
      thinking.
    - **Harmony (OpenAI GPT-OSS 120B, GPT-OSS 20B)**: Accepts only `'low'`,
      `'medium'`, or `'high'`. Does not support `'none'`, `false`, or integer values
      — using these will return an error (e.g., "Invalid reasoning effort: none").
      When omitted, defaults to `'medium'`. Lower effort produces faster responses
      with shorter reasoning.
    """

    reasoning_history: Optional[Literal["disabled", "interleaved", "preserved"]]
    """
    Controls how historical assistant reasoning content is included in the prompt
    for multi-turn conversations.

    **Accepted values:**

    - `null`: Use model/template default behavior (for **GLM-4.7**, the
      model/template default is `'interleaved'`, i.e. historical reasoning is
      cleared by default)
    - `'disabled'`: Strip `reasoning_content` from all messages before prompt
      construction
    - `'interleaved'`: Strip `reasoning_content` from messages up to (and including)
      the last user message
    - `'preserved'`: Preserve historical `reasoning_content` across the conversation

    **Model support:**

    | Model            | Default         | Supported values                             |
    | ---------------- | --------------- | -------------------------------------------- |
    | Kimi K2.7        | `'preserved'`   | `'disabled'`, `'interleaved'`, `'preserved'` |
    | Kimi K2.6        | `'interleaved'` | `'disabled'`, `'interleaved'`, `'preserved'` |
    | Kimi K2 Instruct | `'preserved'`   | `'disabled'`, `'interleaved'`, `'preserved'` |
    | MiniMax M2       | `'interleaved'` | `'disabled'`, `'interleaved'`                |
    | GLM-5.2          | `'interleaved'` | `'disabled'`, `'interleaved'`, `'preserved'` |
    | GLM-4.7          | `'interleaved'` | `'disabled'`, `'interleaved'`, `'preserved'` |
    | GLM-4.6          | `'interleaved'` | `'disabled'`, `'interleaved'`                |
    | Qwen 3.6         | `'preserved'`   | `'disabled'`, `'preserved'`                  |
    | DeepSeek V4      | `'interleaved'` | `'interleaved'`                              |

    For other models, refer to the model provider's documentation.

    **Note:** This parameter controls prompt formatting only. To disable reasoning
    computation entirely, use `reasoning_effort='none'`.
    """

    repetition_penalty: Optional[float]
    """Applies a penalty to repeated tokens to discourage or encourage repetition.

    A value of `1.0` means no penalty, allowing free repetition. Values above `1.0`
    penalize repetition, reducing the likelihood of repeating tokens. Values between
    `0.0` and `1.0` reward repetition, increasing the chance of repeated tokens. For
    a good balance, a value of `1.2` is often recommended. Note that the penalty is
    applied to both the generated output and the prompt in decoder-only models.

    Required range: `0 <= x <= 2`
    """

    response_format: Optional[ResponseFormat]
    """Allows to force the model to produce specific output format.

    Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the
    message the model generates is valid JSON.

    If `"type"` is `"json_schema"`, a JSON schema must be provided. E.g.,
    `response_format = {"type": "json_schema", "json_schema": <json_schema>}`.

    Important: when using JSON mode, it's crucial to also instruct the model to
    produce JSON via a system or user message. Without this, the model may generate
    an unending stream of whitespace until the generation reaches the token limit,
    resulting in a long-running and seemingly "stuck" request.

    Also note that the message content may be partially cut off if
    `finish_reason="length"`, which indicates the generation exceeded `max_tokens`
    or the conversation exceeded the max context length. In this case the return
    value might not be a valid JSON.
    """

    return_token_ids: Optional[bool]
    """Return token IDs alongside text to avoid retokenization drift."""

    safe_tokenization: Optional[bool]
    """
    When true, special tokens in user-provided content are never interpreted as
    actual special tokens during tokenization. This prevents prompt injection via
    special token strings (e.g. <|im_start|>, <｜ User ｜>). Supported for models
    using Jinja or HuggingFace chat templates with HuggingFace tokenizers. Explicit
    true returns an error if the model does not support it, or if combined with
    custom_chat_template on HuggingFace-backed models. Note: prompt_truncate_len is
    not applied when safe_tokenization is enabled. When omitted, safe tokenization
    is enabled by default on a best-effort basis: it is applied only where the model
    supports it and the request is text-only with no custom_chat_template and no
    prompt_truncate_len, and otherwise falls back to normal tokenization.
    """

    sampling_mask: Optional[Literal["count", "non_zero_list", "non_zero_buffer"]]
    """Opt-in sampling mask metadata for generated tokens.

    When set to `"count"`, each generated token in the new logprobs format includes
    the number of token logits still eligible for sampling after filters such as
    top_p and top_k are applied. `"non_zero_list"` additionally returns active token
    IDs in `sampling_mask`; `"non_zero_buffer"` additionally returns a
    base64-encoded little-endian uint32 buffer of active token IDs. Non-zero
    payloads are omitted for positions with more active tokens than 1000.
    """

    seed: Optional[int]
    """Random seed for deterministic sampling."""

    service_tier: Literal["auto", "default", "flex", "priority"]
    """The service tier to use for the request.

    Specifies the processing type used for serving the request. Only "priority" is
    supported, while all other values will be treated as "default" tier.
    """

    speculation: Union[str, Iterable[int], None]
    """Speculative decoding prompt or token IDs to speed up generation."""

    stop: Union[str, SequenceNotStr[str], None]
    """Up to 4 sequences where the API will stop generating further tokens.

    The returned text will NOT contain the stop sequence.
    """

    stream_options: Optional[StreamOptions]
    """Options for streaming responses.

    Only valid with `stream=true`. Fireworks includes a final SSE chunk carrying
    usage totals by default; set `include_usage=false` to opt out. The
    `buffer_tokens` / `buffer_ms` / `buffer_mode` fields coalesce SSE chunks by
    token count and/or time (vLLM backend; override the deployment default).
    """

    temperature: Optional[float]
    """What sampling temperature to use, between 0 and 2.

    Higher values like 0.8 will make the output more random, while lower values like
    0.2 will make it more focused and deterministic.

    We generally recommend altering this or top_p but not both.

    Required range: `0 <= x <= 2`

    Example: `1`
    """

    thinking: Optional[Thinking]
    """Configuration for enabling extended thinking (Anthropic-compatible format).

    This is an alternative to `reasoning_effort` for controlling reasoning behavior.

    **Format:**

    - `{"type": "enabled"}` - Enable thinking (equivalent to
      `reasoning_effort: true`)
    - `{"type": "enabled", "budget_tokens": <int>}` - Enable thinking with a token
      budget (equivalent to `reasoning_effort: <int>`). Must be >= 1024.
    - `{"type": "enabled", "keep": "all"}` - Enable thinking and preserve all
      historical reasoning content in the prompt (equivalent to
      `reasoning_history: "preserved"`).
    - `{"type": "disabled"}` - Disable thinking (equivalent to
      `reasoning_effort: "none"`)

    **Precedence with `reasoning_effort`:** `thinking.effort` (when set) overrides
    `reasoning_effort`; otherwise, for `type=enabled`, `reasoning_effort` is used as
    the effort level. `type=disabled` always disables thinking.
    """

    tool_choice: ToolChoice
    """Controls which (if any) tool is called by the model.

    - `none`: the model will not call any tool and instead generates a message.
    - `auto`: the model can pick between generating a message or calling one or more
      tools.
    - `required` (alias: `any`): the model must call one or more tools. To force a
      specific function, pass an object of the form
      `{ "type": "function", "name": "my_function" }` or
      `{ "type": "function", "function": { "name": "my_function" } }` for OpenAI
      compatibility.
    - To restrict tool calls to a subset of the provided tools while keeping the
      full tool list in the prompt (preserving prompt cache hits), pass
      `{ "type": "allowed_tools", "allowed_tools": { "mode": "auto"|"required", "tools": [{ "type": "function", "function": { "name": "..." } }] } }`.
      Equivalent OpenAI Responses-style flat form is also accepted:
      `{ "type": "allowed_tools", "mode": "...", "tools": [...] }`.
    """

    tools: Iterable[ChatCompletionTool]
    """A list of tools the model may call.

    Currently, only functions are supported as a tool.

    Use this to provide a list of functions the model may generate JSON inputs for.

    See the our
    [model library](https://app.fireworks.ai/models/?filter=LLM&functionCalling=true)
    for the list of supported models
    """

    top_k: Optional[int]
    """
    Top-k sampling is another sampling method where the k most probable next tokens
    are filtered and the probability mass is redistributed among only those k next
    tokens. The value of k controls the number of candidates for the next token at
    each step during text generation. Must be between 0 and 100.

    Required range: `0 <= x <= 100`

    Example: `50`
    """

    top_logprobs: Optional[int]
    """
    An integer specifying the number of most likely tokens to return at each token
    position, each with an associated log probability. Must be between 0 and the
    deployment's `--max-logprobs` limit (5 by default).

    When `logprobs` is set, `top_logprobs` can be used to modify how many top log
    probabilities are returned. If `top_logprobs` is not set, the API will return up
    to `logprobs` tokens per position.
    """

    top_p: Optional[float]
    """
    An alternative to sampling with temperature, called nucleus sampling, where the
    model considers the results of the tokens with top_p probability mass. So 0.1
    means only the tokens comprising the top 10% probability mass are considered.

    We generally recommend altering this or temperature but not both.

    Required range: `0 <= x <= 1`

    Example: `1`
    """

    typical_p: Optional[float]
    """Typical-p sampling is an alternative to nucleus sampling.

    It considers the most typical tokens whose cumulative probability is at most
    typical_p.

    Required range: `0 <= x <= 1`
    """

    user: Optional[str]
    """
    A unique identifier representing your end-user, which can help monitor and
    detect abuse.
    """


class FunctionCallFunctionNameSpec(TypedDict, total=False):
    name: Required[str]


FunctionCall: TypeAlias = Union[Literal["auto", "none"], FunctionCallFunctionNameSpec]


class Function(TypedDict, total=False):
    name: Required[str]
    """The name of the function to be called.

    Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length
    of 64.
    """

    description: Optional[str]
    """
    A description of what the function does, used by the model to choose when and
    how to call the function.
    """

    parameters: Dict[str, object]
    """The parameters the function accepts, described as a JSON Schema object.

    The JSON Schema object should have the following structure:

    ```json
    {
      "type": "object",
      "required": ["param1", "param2"],
      "properties": {
        "param1": {
          "type": "string",
          "description": "..."
        },
        "param2": {
          "type": "number",
          "description": "..."
        }
      }
    }
    ```

    - The `type` field must be `"object"`.
    - The `required` field is an array of strings indicating which parameters are
      required.
    - The `properties` field is a map of property names to their definitions, where
      each property is an object with `type` (string) and `description` (string)
      fields.

    To describe a function that accepts no parameters, provide the value:

    ```json
    { "type": "object", "properties": {} }
    ```
    """

    strict: Optional[bool]


class PredictionPredictedOutputContentUnionMember1ImageURL(TypedDict, total=False):
    url: Required[str]
    """Image link or base64 data URI.

    `mm_file://{file_id}` is also accepted for assets uploaded via the Files API.
    """

    detail: Optional[str]
    """Detail level for image understanding.

    One of `low` / `default` / `high` (model-specific defaults table). Used to pick
    a default `max_long_side_pixel` when that field is absent.
    """

    max_long_side_pixel: Optional[int]
    """Per-image cap on the long side after resizing.

    When omitted, the model derives a default from `detail`. Currently honored by
    MiniMax M3 VL preprocessing; other VL models ignore this field. See the M3 VL
    preprocessing spec (2026-05-29) for the full 3-step resize semantics (long-side
    cap → short-side floor at 112 px → hard total-pixel cap).
    """


class PredictionPredictedOutputContentUnionMember1VideoURL(TypedDict, total=False):
    url: Required[str]
    """Video link or base64 data URI.

    `mm_file://{file_id}` is accepted for assets uploaded via the Files API
    (recommended for files > 50 MB).
    """

    detail: Optional[str]
    """Detail level for video understanding. One of `low` / `default` / `high`."""

    fps: Optional[float]
    """
    Frame sampling rate, in [0.2, 5] Hz for MiniMax M3 VL (was [0.5, 2] in the
    pre-2026-05-29 spec). Higher values are more sensitive to motion at the cost of
    more tokens; lower values are cheaper but less responsive to fast scene changes.
    Equivalent to `sample_fps` on non-M3 video models.
    """

    max_frames: Optional[int]

    max_long_side_pixel: Optional[int]
    """Per-frame cap on the long side after resizing.

    When omitted, the model derives a default from `detail`. Currently honored by
    MiniMax M3 VL preprocessing; other VL models ignore this field.
    """

    sample_fps: Optional[float]
    """Frame sampling rate (Kimi K2.5 VL legacy name).

    For MiniMax M3 VL prefer the canonical `fps` field.
    """

    spatial_limit: Optional[int]


class PredictionPredictedOutputContentUnionMember1(TypedDict, total=False):
    type: Required[str]

    image_url: Optional[PredictionPredictedOutputContentUnionMember1ImageURL]

    text: Optional[str]

    video_url: Optional[PredictionPredictedOutputContentUnionMember1VideoURL]


class PredictionPredictedOutput(TypedDict, total=False):
    """OpenAI-compatible struct for the "speculation" field."""

    content: Required[Union[str, Iterable[PredictionPredictedOutputContentUnionMember1]]]

    type: Literal["content"]


Prediction: TypeAlias = Union[PredictionPredictedOutput, str]


class ResponseFormat(TypedDict, total=False):
    """Allows to force the model to produce specific output format.

    Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is valid JSON.

    If `"type"` is `"json_schema"`, a JSON schema must be provided. E.g., `response_format = {"type": "json_schema", "json_schema": <json_schema>}`.

    Important: when using JSON mode, it's crucial to also instruct the model to produce JSON via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly "stuck" request.

    Also note that the message content may be partially cut off if `finish_reason="length"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length. In this case the return value might not be a valid JSON.
    """

    type: Required[Literal["json_object", "json_schema", "grammar", "text"]]

    grammar: Optional[str]

    json_schema: Union[Dict[str, object], str, None]

    schema: Union[Dict[str, object], str, None]


class StreamOptions(TypedDict, total=False):
    """Options for streaming responses.

    Only valid with ``stream=true``. Fireworks includes a final SSE chunk carrying usage totals by default; set ``include_usage=false`` to opt out. The ``buffer_tokens`` / ``buffer_ms`` / ``buffer_mode`` fields coalesce SSE chunks by token count and/or time (vLLM backend; override the deployment default).
    """

    buffer_mode: Optional[Literal["any", "all"]]
    """
    When both buffer_tokens and buffer_ms are set: 'any' flushes when either
    threshold is reached; 'all' flushes only when both are. Overrides the deployment
    default when set; defaults to 'any'.
    """

    buffer_ms: Optional[float]
    """
    Coalesce streaming SSE chunks for up to this many milliseconds before flushing a
    merged chunk. 0 disables the time threshold. Honored only on the vLLM backend;
    overrides the deployment default when set.
    """

    buffer_tokens: Optional[int]
    """
    Coalesce streaming SSE chunks until this many text deltas (~tokens) accumulate
    before flushing a merged chunk. 0 disables the token threshold. Honored only on
    the vLLM backend; overrides the deployment default when set.
    """

    include_internal_content: Optional[bool]
    """
    When true, include an `internal_content` object (currently `token_id`) inside
    each streaming delta — equivalent to `return_token_ids`, emitted under
    `choices[].delta.internal_content`. Omitted entirely from response chunks when
    false.
    """

    include_usage: Optional[bool]
    """
    Whether to include a trailing SSE chunk with usage totals (with an empty
    `choices` array). Unlike the OpenAI spec, Fireworks includes usage by default
    for streaming responses; set this to `false` to opt out. When emitted, usage
    rides a separate final chunk (before `data: [DONE]`), not the chunk carrying
    `finish_reason`.
    """


class ThinkingThinkingConfigEnabled(TypedDict, total=False):
    """Configuration for enabling extended thinking (Anthropic-compatible format)."""

    budget_end_str: Optional[str]
    """
    Natural-language transition phrase that the model is forced to emit just before
    the end-thinking token (`</think>`) when `budget_tokens` is exhausted. This
    produces a more natural conclusion than a hard token slam (matches vLLM's
    `reasoning_end_str` behavior). Defaults to a built-in phrase. Set to "" to
    disable the bridge and force `</think>` immediately. Only meaningful when
    `budget_tokens` is set.
    """

    budget_tokens: Optional[int]
    """Determines how many tokens the model can use for its internal reasoning process.

    Larger budgets can enable more thorough analysis for complex problems, improving
    response quality. Must be >= 1024 if specified.
    """

    effort: Union[Literal["low", "medium", "high", "xhigh", "max", "none", "adaptive"], int, bool, None]
    """Reasoning effort level (Kimi/Moonshot spec).

    Accepts the same values as top-level `reasoning_effort`; when set it takes
    precedence over (overwrites) `reasoning_effort`.
    """

    keep: Optional[Literal["all"]]
    """Controls whether historical reasoning content is preserved in the prompt.

    When set to `"all"`, all previous assistant turns' reasoning_content is included
    in the rendered prompt (equivalent to `reasoning_history: "preserved"`). When
    omitted (null), the model uses its default history behavior. Only valid when
    `type` is `"enabled"`.
    """

    type: Literal["enabled"]


class ThinkingThinkingConfigDisabled(TypedDict, total=False):
    """Configuration for disabling extended thinking (Anthropic-compatible format)."""

    type: Required[Literal["disabled"]]


class ThinkingThinkingConfigAdaptive(TypedDict, total=False):
    """Configuration that lets the model decide whether to think (MiniMax M3).

    Per the M3 API spec (§1.4), `{"type": "adaptive"}` is M3's default — the model
    decides whether to emit a thinking phase. No forced first token is applied.
    Currently accepted only by MiniMax M3; other model families reject it.
    """

    type: Required[Literal["adaptive"]]


Thinking: TypeAlias = Union[
    ThinkingThinkingConfigEnabled, ThinkingThinkingConfigDisabled, ThinkingThinkingConfigAdaptive
]


class ToolChoiceFunctionSelectionFunction(TypedDict, total=False):
    name: Required[str]


class ToolChoiceFunctionSelection(TypedDict, total=False):
    type: Required[Literal["function"]]

    function: Optional[ToolChoiceFunctionSelectionFunction]


class ToolChoiceAllowedToolsSelectionAllowedTools(TypedDict, total=False):
    """OpenAI-compatible allowed_tools sub-object.

    See https://platform.openai.com/docs/guides/function-calling#tool-choice

    The ``tools`` list mirrors the ``tools`` list passed at the top level: each
    entry must be ``{"type": "function", "function": {"name": "<fn>"}}``.
    Fireworks only supports function tools today, so other ``type`` values are
    rejected.
    """

    mode: Required[Literal["auto", "required"]]
    """
    `auto` lets the model pick between generating a message and calling one of the
    allowed tools. `required` forces the model to call one of them.
    """

    tools: Required[Iterable[Dict[str, object]]]
    """A list of tool references the model is allowed to invoke.

    Each entry must be of the form
    `{"type": "function", "function": {"name": "..."}}`. The referenced tools must
    also appear in the top-level `tools` list.
    """


class ToolChoiceAllowedToolsSelection(TypedDict, total=False):
    """OpenAI-compatible ``tool_choice.type = "allowed_tools"`` selection.

    Restricts the model's tool calls to a subset of the top-level ``tools`` list
    *without modifying the prompt*, preserving prompt cache hits. The full set
    of tool definitions is still rendered into the prompt for the model; only
    the grammar (and downstream parsing) is constrained to the allowed subset.
    """

    allowed_tools: Required[ToolChoiceAllowedToolsSelectionAllowedTools]
    """OpenAI-compatible allowed_tools sub-object.

    See https://platform.openai.com/docs/guides/function-calling#tool-choice

    The `tools` list mirrors the `tools` list passed at the top level: each entry
    must be `{"type": "function", "function": {"name": "<fn>"}}`. Fireworks only
    supports function tools today, so other `type` values are rejected.
    """

    type: Required[Literal["allowed_tools"]]


ToolChoice: TypeAlias = Union[
    Literal["auto", "none", "any", "required"], ToolChoiceFunctionSelection, ToolChoiceAllowedToolsSelection
]


class CompletionCreateParamsNonStreaming(CompletionCreateParamsBase, total=False):
    stream: Optional[Literal[False]]
    """Whether to stream back partial progress.

    If set, tokens will be sent as data-only
    [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
    as they become available, with the stream terminated by a `data: [DONE]`
    message.
    """


class CompletionCreateParamsStreaming(CompletionCreateParamsBase):
    stream: Required[Literal[True]]
    """Whether to stream back partial progress.

    If set, tokens will be sent as data-only
    [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
    as they become available, with the stream terminated by a `data: [DONE]`
    message.
    """


CompletionCreateParams = Union[CompletionCreateParamsNonStreaming, CompletionCreateParamsStreaming]
